// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BehaviorConfig = { sound_enabled: boolean, fullscreen_skip: boolean, afk_skip_enabled: boolean, afk_threshold_minutes: number, auto_start: boolean, };
