// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BehaviorConfig = {
  sound_enabled: boolean;
  fullscreen_skip: boolean;
  auto_start: boolean;
};
