// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reason a rest cycle was `suppressed` (and only suppressed). Other
 * outcomes always store `reason = NULL`.
 */
export type CycleReason = "fullscreen" | "schedule" | "afk" | "process_whitelisted";
