// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EyeCareIndex } from "./EyeCareIndex";
import type { ReasonBreakdown } from "./ReasonBreakdown";
import type { RhythmPayload } from "./RhythmPayload";
import type { RibbonEntry } from "./RibbonEntry";

/**
 * Today's outcome roll-up + 24h ribbon + Eye-Care Index + rhythm cards.
 * Returned by the `statistics_cycle_outcomes` IPC command.
 */
export type CycleOutcomesPayload = { timezone: string, today_taken: number, today_skipped: number, today_suppressed: number, today_adherence_rate: number | null, today_reason_breakdown: ReasonBreakdown, last_24h_ribbon: Array<RibbonEntry>, eye_care_index: EyeCareIndex, rhythm: RhythmPayload, 
/**
 * Always `true` in v0.6 to render the Beta label / tooltip.
 */
is_beta: boolean, };
