// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of a single rest cycle event. The schema persists the
 * `snake_case` form ("taken", "skipped", "suppressed").
 */
export type CycleOutcome = "taken" | "skipped" | "suppressed";
