// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Platform detector capabilities reported to the Settings UI.
 *
 * Each field indicates whether the underlying platform API supports the
 * corresponding detection feature. Settings uses these to gray out controls
 * for unavailable features.
 */
export type DetectorCapabilities = { afk_detection_supported: boolean, foreground_process_detection_supported: boolean, fullscreen_detection_supported: boolean, };
