// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DetectorCapabilities = { afk_detection_supported: boolean, foreground_process_detection_supported: boolean, };
