// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Component contributions to the v0.6 Eye-Care Index.
 */
export type EyeCareComponents = { adherence: number, longest_session: number, };
