// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EyeCareComponents } from "./EyeCareComponents";

/**
 * Eye-Care Index (Beta) summary. `score` is `None` when not computable
 * (warming up at start of day, or schedule-inactive "rest day").
 */
export type EyeCareIndex = { score: number | null, is_warming_up: boolean, is_rest_day: boolean, components: EyeCareComponents, };
