// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HotkeyBindingStatus } from "./HotkeyBindingStatus";
import type { MacosAccessibilityStatus } from "./MacosAccessibilityStatus";

export type HotkeyStatus = { bindings: Array<HotkeyBindingStatus>, macos_accessibility: MacosAccessibilityStatus, last_error: string | null, };
