// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HotkeyAction } from "./HotkeyAction";
import type { HotkeyBindingState } from "./HotkeyBindingState";

export type HotkeyBindingStatus = { action: HotkeyAction, shortcut: string, state: HotkeyBindingState, message: string | null, };
