// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HotkeysConfig = { start_rest: string, skip_rest: string, toggle_pause: string, };
