// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pomodoro pacing knobs. Only consulted when `TimerConfig::mode ==
 * TimerMode::Pomodoro`; the cycle counter itself is runtime-only and reset on
 * every app start (matches the "session = single run" Pomodoro tradition).
 */
export type PomodoroConfig = { focus_minutes: number, short_break_minutes: number, long_break_minutes: number, cycles_per_long: number, };
