// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pomodoro runtime snapshot. Only present when `StatePayload::mode ==
 * TimerMode::Pomodoro`.
 *
 * - `cycle_index`: 1-based ordinal of the *current* focus session in this
 *   long-break cycle. Range `1..=cycles_per_long`.
 * - `is_long_break`: true while the user is in the long-break Resting after
 *   completing the `cycles_per_long`-th focus.
 */
export type PomodoroStatePayload = { cycle_index: number, cycles_per_long: number, is_long_break: boolean, };
