// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Breakdown of today's `suppressed` cycles by reason.
 */
export type ReasonBreakdown = { fullscreen: number, schedule: number, afk: number, process_whitelisted: number, };
