// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Streak metrics derived from daily `taken` counts vs the user's
 * personal threshold.
 */
export type RhythmPayload = { current_streak_days: number, best_streak_days: number, threshold: number, };
