// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CycleOutcome } from "./CycleOutcome";
import type { CycleReason } from "./CycleReason";

/**
 * One entry in the last-24h adherence ribbon.
 */
export type RibbonEntry = { 
/**
 * RFC3339 UTC timestamp; frontend converts to local time.
 */
occurred_at: string, outcome: CycleOutcome, reason: CycleReason | null, };
