// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weekly schedule controlling when rest reminders are allowed to surface.
 *
 * `active_days` is indexed by `chrono::Weekday::num_days_from_monday`:
 * `0 = Mon`, `1 = Tue`, ..., `6 = Sun`.
 */
export type ScheduleConfig = { enabled: boolean, active_days: [boolean, boolean, boolean, boolean, boolean, boolean, boolean], };
