// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PomodoroStatePayload } from "./PomodoroStatePayload";
import type { TimerMode } from "./TimerMode";

/**
 * Payload for the `state_changed` IPC event.
 *
 * Emitted by `TimerService` whenever the timer state transitions or the
 * remaining time crosses a UI-relevant threshold.
 */
export type StateChangedPayload = { state: string, remaining_secs: number, work_minutes: number, rest_seconds: number, mode: TimerMode, pomodoro: PomodoroStatePayload | null, };
