// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatPersistenceKind } from "./StatPersistenceKind";

/**
 * Emitted as `stat_persistence_error` when the stat writer task cannot
 * persist a draft. Replaces the pre-v0.7 `warn!`-only behavior so users
 * notice missing rest history instead of finding it later.
 */
export type StatPersistenceErrorPayload = { kind: StatPersistenceKind, 
/**
 * RFC3339 UTC timestamp of the failure (not the draft's own
 * `occurred_at`, which may differ).
 */
occurred_at: string, 
/**
 * Diagnostic string lifted from the underlying `AppError`. Safe to
 * surface in the UI: the format is the same as `AppError`'s `Display`.
 */
message: string, };
