// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatBucket } from "./StatBucket";

/**
 * Daily, weekly, and monthly trend data for the Statistics page.
 */
export type StatisticsTrendPayload = { timezone: string, daily: Array<StatBucket>, weekly: Array<StatBucket>, monthly: Array<StatBucket>, total_sessions: number, total_rest_secs: number, };
