// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kind of stat write failed, so the UI can phrase the error and
 * the user can decide whether to retry or restart.
 */
export type StatPersistenceKind = "rest_session" | "cycle_event" | "queue_overflow";
