// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PomodoroStatePayload } from "./PomodoroStatePayload";
import type { TimerMode } from "./TimerMode";

/**
 * Shared timer payload placeholder for commands and events.
 */
export type StatePayload = { state: string, remaining_secs: number, work_minutes: number, rest_seconds: number, mode: TimerMode, pomodoro: PomodoroStatePayload | null, };
