// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated statistics bucket exposed to the frontend.
 */
export type StatBucket = { label: string, rest_sessions: number, total_rest_secs: number, };
