// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimerConfig = { work_minutes: number, rest_seconds: number, pre_alert_seconds: number, alert_timeout_seconds: number, };
