// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which rhythm the timer uses.
 *
 * `TwentyTwentyTwenty` keeps the existing eye-care behavior (`work_minutes`
 * ⇒ `rest_seconds`). `Pomodoro` follows classic 25/5/15 pacing using
 * `PomodoroConfig`; cycle counter is held in the timer runtime, not in TOML.
 */
export type TimerMode = "twenty_twenty_twenty" | "pomodoro";
